Assignment/associations
saintPOPPY/lecis233 pull request #4
Opened 2023-03-01 05:28 UTC by saintPOPPY

Objectives

Get familiar with relating multiple tables together using Eloquent Model. We will be adding reviews to our products. Thus, a product will have many reviews and a review will belong to a product.

Preparing to do work

You must watch all my lectures before beginning or asking for help.
Make sure your previous assignment has been graded and merged into the main branch by me. 
Pull your main branch to assure it is updated on your local repo
Create a branch in your repo called: assignment/associations
Be liberal with your commits. When you finish a small piece of functionality then create a commit for it.
ie. 'Generated controller', 'index action gets all products', 'Show action gets one product', 'Added Bootstrap', 'Layout implemented' are just some examples.
You will add features to your existing crud-app
Specifications

Create a new migration, table (reviews), model (Review)
Migration details:
id, timestamps - already provided by migration generator
Added by you:
comment (text)
rating (integer)
product_id (integer)
Assure you add an index for product_id
In the Product model, define a has_many relationship with reviews
In the Review model, define a belongs_to relationship with product
Add a new seeder for Reviews
Create reviews, use faker for data
Associate the reviews to some of the existing products (not all products should have reviews)
Note: seeder running order is important, assure the products seeder runs before the reviews seeder
Get into Tinker and "tinker" around with relationships.
Getting familiar with code necessary to load records and see related data is important before you start coding in the application.
On the product show page
display a small form to add a review (comment and rating)
rating will be acquired by a select list displaying numbers 1-5
Hint: use a hidden form element that holds the product_id which gets submitted with the form
Comment is required and must be validated. Show error, if invalid.
below the form will be a list/table of reviews
for each row display comment and number of stars the review is.
You can use an html entity for star ([https://www.toptal.com/designers/htmlarrows/symbols/black-star/https://www.toptal.com/designers/htmlarrows/symbols/black-star/Links to an external site.](https://www.toptal.com/designers/htmlarrows/symbols/black-star/https://www.toptal.com/designers/htmlarrows/symbols/black-star/)) or use an image of your choice.
If no reviews have been given yet, display a message saying "No reviews yet"
You should be able to delete a review (with JavaScript confirmation)
You'll need a ReviewController with actions for store and destroy
Note: in this particular case, you'll be redirecting back to product show page after you create or delete a review
Note: I do not want to see an N+1 problem when querying for data
![deleteconf](https://user-images.githubusercontent.com/37557946/222053019-7a6c9ad0-ff96-41c8-89a7-4bbcdd50fb47.PNG)
![list](https://user-images.githubusercontent.com/37557946/222053022-c85b49d2-6571-4dcf-8d10-eaa1d984e8b9.PNG)
![showpage](https://user-images.githubusercontent.com/37557946/222053025-f72dfb35-d35b-41fb-83cc-695268146d77.PNG)

2023-03-01 18:37 UTC, kblake requested changes
Add a picture where there are no reviews yet

2023-03-01 18:37 UTC, kblake commented on crud-app/app/Http/Controllers/ProductController.php
> +        $products = Product::query()->orderBy($sortBy, $direction);
No specification to sort. So, remove that code. There should be eager loading code in your show action though

2023-03-01 18:37 UTC, kblake commented on crud-app/app/Models/Product.php
> +    public function review() {
Needs to be a plural name

2023-03-01 18:37 UTC, kblake commented on crud-app/resources/views/products/show.blade.php
> +            <td>{{ $review->rating }}&starf;</td>
need to display rating number of actual star entities

2023-03-13 18:16 UTC, mledevelop commented on crud-app/app/Http/Controllers/ProductController.php
> +        $products = Product::query()->orderBy($sortBy, $direction);
removed sorting, however am having trouble figuring out eager loading the products

2023-03-13 18:16 UTC, saintPOPPY commented on crud-app/app/Models/Product.php
> +    public function review() {
modified

2023-03-13 18:17 UTC, mledevelop commented on crud-app/resources/views/products/show.blade.php
> +            <td>{{ $review->rating }}&starf;</td>
difficulties figuring out HTML entity usage

2023-03-13 22:55 UTC, kblake requested changes

2023-03-13 22:55 UTC, kblake commented on crud-app/app/Http/Controllers/ProductController.php
> +        return response(view('products.index', ['products' => $products->paginate(10)]));
Use `Product::paginate(10)` instead of `Product::query()` and then a paginate.

2023-03-13 22:55 UTC, kblake commented on crud-app/app/Http/Controllers/ReviewController.php
> +    }
Not used? so remove

2023-03-13 22:55 UTC, kblake commented on crud-app/resources/views/products/show.blade.php
> +            <td>{{ $reviews->rating }}&starf;</td>
Need to print the number of stars using either a for loop or str_repeat

2023-03-13 22:55 UTC, kblake commented on crud-app/app/Http/Controllers/ProductController.php
> +        $products = Product::query()->orderBy($sortBy, $direction);
nothing to eager load on the index page

2023-03-13 22:55 UTC, kblake commented on crud-app/app/Http/Controllers/ProductController.php
> +        $products = Product::query()->orderBy($sortBy, $direction);
for the `show` action, you do need to eager load the reviews for the product

2023-03-14 00:10 UTC, kblake requested changes
Need to eager load reviews in the show action of the ProductController

2023-03-14 16:40 UTC, kblake approved these changes
:shipit:

2023-03-14 16:40 UTC, merged